### ISSUE TITLE
Need help to build the snap

### ISSUE THREAD

**Issue by soumyaDghosh** [xlmnxp/blue-recorder#62]
I have been trying to build the snap package. But, it's showing me this error.

```bash
(blue-recorder:8518): Gtk-WARNING **: 10:18:45.936: gtk_window_set_titlebar() called on a realized window
thread 'main' panicked at src/main.rs:57:10:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x60ef73ee6256 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c4bd387f9f3f544
   1:     0x60ef73f13240 - core::fmt::write::h938c332fdab924eb
   2:     0x60ef73ee2b7f - std::io::Write::write_fmt::h4a694b02e44e6363
   3:     0x60ef73ee6034 - std::sys_common::backtrace::print::ha888e6736b0bc71f
   4:     0x60ef73ee78b7 - std::panicking::default_hook::{{closure}}::he19a7f79f7beab5e
   5:     0x60ef73ee7619 - std::panicking::default_hook::h67efe04e9a5d446e
   6:     0x60ef73ee7d48 - std::panicking::rust_panic_with_hook::h49021cdbc4b22349
   7:     0x60ef73ee7c22 - std::panicking::begin_panic_handler::{{closure}}::hfbf601f3d8c62d13
   8:     0x60ef73ee6756 - std::sys_common::backtrace::__rust_end_short_backtrace::h98dd020b6e913806
   9:     0x60ef73ee7974 - rust_begin_unwind
  10:     0x60ef739d6ac5 - core::panicking::panic_fmt::h0d3f1893e38be419
  11:     0x60ef739d6fb3 - core::result::unwrap_failed::h1356562ef8bc898c
  12:     0x60ef73a9f237 - blue_recorder::build_ui::h9db3e9ff584a536c
  13:     0x60ef73aed821 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::h1e9155974122eee8
  14:     0x71b730c8832f - g_closure_invoke
  15:     0x71b730c9e2bb - <unknown>
  16:     0x71b730ca0f83 - <unknown>
  17:     0x71b730caa3f9 - g_signal_emit_valist
  18:     0x71b730caa4c3 - g_signal_emit
  19:     0x71b730b5eee8 - <unknown>
  20:     0x71b730b5f066 - g_application_run
  21:     0x60ef73af6378 - <O as gio::application::ApplicationExtManual>::run::h801d93fb7bc201f9
  22:     0x60ef73a9a505 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::h233d84265873813a
  23:     0x60ef73a896d6 - <futures_lite::future::PollFn<F> as core::future::future::Future>::poll::h09602e63b46a66ff
  24:     0x60ef73ab3a9c - async_global_executor::executor::block_on::hfa2d177c5c00ecd0
  25:     0x60ef73ae8b36 - async_std::task::builder::Builder::blocking::hd25a062b24122f6f
  26:     0x60ef73aa0d7c - blue_recorder::main::h7fd76a18e43aac7e
  27:     0x60ef73ae3e23 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdcbdae4c952a0822
  28:     0x60ef73abd409 - std::rt::lang_start::{{closure}}::he6fabb8d45e46cd9
  29:     0x60ef73edb721 - std::rt::lang_start_internal::hc3f700406209db2c
  30:     0x60ef73aa0db5 - main
  31:     0x71b72fa74d90 - <unknown>
  32:     0x71b72fa74e40 - __libc_start_main
  33:     0x60ef739d7275 - _start
  34:                0x0 - <unknown>
```

I have added the `po` files and also the `PO_DIR` environment variable. Please help me fix this. I don't think it'll be tough/

**Comment by Silenke2x2** [comment]
I have the same problem too: 
**$ blue-recorder**
```
gtk_window_set_titlebar() called on a realized window
thread 'main' panicked at src/main.rs:57:10:
called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "Нет такого файла или каталога" }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

**Comment by poperigby** [comment]
Very similar error message here, when trying to package this for Nix:

```
(blue-recorder:1430646): Gtk-WARNING **: 17:54:58.305: gtk_window_set_titlebar() called on a realized window
thread 'main' panicked at src/main.rs:55:10:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: blue_recorder::build_ui
   4: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
   5: g_closure_invoke
   6: signal_emit_unlocked_R.isra.0
   7: signal_emit_valist_unlocked
   8: g_signal_emit_valist
   9: g_signal_emit
  10: g_application_real_local_command_line
  11: g_application_run
  12: <O as gio::application::ApplicationExtManual>::run
  13: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
  14: <futures_lite::future::PollFn<F> as core::future::future::Future>::poll
  15: async_std::task::builder::Builder::blocking
  16: blue_recorder::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x559ad3adf6b6 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9754a6437f1de22a
   1:     0x559ad3b3868b - core::fmt::write::hb706a393bb60a06f
   2:     0x559ad3ae7969 - std::io::Write::write_fmt::h9b447dc5d824d0bd
   3:     0x559ad3b14876 - std::panicking::default_hook::{{closure}}::h227952daede9dd84
   4:     0x559ad3b14506 - std::panicking::default_hook::h31626ee1feb8ee2a
   5:     0x559ad3b14dd1 - std::panicking::rust_panic_with_hook::h76d2aa694a00748e
   6:     0x559ad3adfce3 - std::panicking::begin_panic_handler::{{closure}}::h8855a344ffa1638b
   7:     0x559ad3adf8c9 - std::sys::backtrace::__rust_end_short_backtrace::h3110d0cbfbf26886
   8:     0x559ad3b149b4 - rust_begin_unwind
   9:     0x559ad3628c95 - core::panicking::panic_nounwind_fmt::h8711c6114508ebf8
  10:     0x559ad3628d22 - core::panicking::panic_nounwind::h1adbd03b05fc3727
  11:     0x559ad3628e06 - core::panicking::panic_cannot_unwind::hb44e051de6abac0c
  12:     0x559ad36c7c43 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::he7805ead02f76379
  13:     0x7f81232f4da8 - g_closure_invoke
  14:     0x7f81233090fc - signal_emit_unlocked_R.isra.0
  15:     0x7f812330aa71 - signal_emit_valist_unlocked
  16:     0x7f8123310542 - g_signal_emit_valist
  17:     0x7f81233105ff - g_signal_emit
  18:     0x7f81230f2920 - g_application_real_local_command_line
  19:     0x7f81230f2ab6 - g_application_run
  20:     0x559ad36c7a56 - <O as gio::application::ApplicationExtManual>::run::h5ad5b4b89b00f063
  21:     0x559ad36e6ba3 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::h0cd3bedbb540ac3e
  22:     0x559ad36c1ad3 - <futures_lite::future::PollFn<F> as core::future::future::Future>::poll::h67a3a8667bf91abd
  23:     0x559ad36f1f1b - async_std::task::builder::Builder::blocking::ha51a286a0b922b13
  24:     0x559ad372430c - blue_recorder::main::h05fec46f585020e9
  25:     0x559ad3729d33 - std::sys::backtrace::__rust_begin_short_backtrace::h00a1fd4b96f972ac
  26:     0x559ad3711459 - std::rt::lang_start::{{closure}}::h8c4342eb2e2bd770
  27:     0x559ad3b173a5 - std::rt::lang_start_internal::h2084fce485147f46
  28:     0x559ad3724345 - main
  29:     0x7f8121ee527e - __libc_start_call_main
  30:     0x7f8121ee5339 - __libc_start_main_alias_2
  31:     0x559ad36290b5 - _start
  32:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
fish: Job 1, 'RUST_BACKTRACE=1 blue-recorder' terminated by signal SIGABRT (Abort)
```

**Comment by xlmnxp** [comment]
> Very similar error message here, when trying to package this for Nix:
> 
> ```
> (blue-recorder:1430646): Gtk-WARNING **: 17:54:58.305: gtk_window_set_titlebar() called on a realized window
> thread 'main' panicked at src/main.rs:55:10:
> called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::result::unwrap_failed
>    3: blue_recorder::build_ui
>    4: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
>    5: g_closure_invoke
>    6: signal_emit_unlocked_R.isra.0
>    7: signal_emit_valist_unlocked
>    8: g_signal_emit_valist
>    9: g_signal_emit
>   10: g_application_real_local_command_line
>   11: g_application_run
>   12: <O as gio::application::ApplicationExtManual>::run
>   13: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
>   14: <futures_lite::future::PollFn<F> as core::future::future::Future>::poll
>   15: async_std::task::builder::Builder::blocking
>   16: blue_recorder::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread 'main' panicked at core/src/panicking.rs:221:5:
> panic in a function that cannot unwind
> stack backtrace:
>    0:     0x559ad3adf6b6 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9754a6437f1de22a
>    1:     0x559ad3b3868b - core::fmt::write::hb706a393bb60a06f
>    2:     0x559ad3ae7969 - std::io::Write::write_fmt::h9b447dc5d824d0bd
>    3:     0x559ad3b14876 - std::panicking::default_hook::{{closure}}::h227952daede9dd84
>    4:     0x559ad3b14506 - std::panicking::default_hook::h31626ee1feb8ee2a
>    5:     0x559ad3b14dd1 - std::panicking::rust_panic_with_hook::h76d2aa694a00748e
>    6:     0x559ad3adfce3 - std::panicking::begin_panic_handler::{{closure}}::h8855a344ffa1638b
>    7:     0x559ad3adf8c9 - std::sys::backtrace::__rust_end_short_backtrace::h3110d0cbfbf26886
>    8:     0x559ad3b149b4 - rust_begin_unwind
>    9:     0x559ad3628c95 - core::panicking::panic_nounwind_fmt::h8711c6114508ebf8
>   10:     0x559ad3628d22 - core::panicking::panic_nounwind::h1adbd03b05fc3727
>   11:     0x559ad3628e06 - core::panicking::panic_cannot_unwind::hb44e051de6abac0c
>   12:     0x559ad36c7c43 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::he7805ead02f76379
>   13:     0x7f81232f4da8 - g_closure_invoke
>   14:     0x7f81233090fc - signal_emit_unlocked_R.isra.0
>   15:     0x7f812330aa71 - signal_emit_valist_unlocked
>   16:     0x7f8123310542 - g_signal_emit_valist
>   17:     0x7f81233105ff - g_signal_emit
>   18:     0x7f81230f2920 - g_application_real_local_command_line
>   19:     0x7f81230f2ab6 - g_application_run
>   20:     0x559ad36c7a56 - <O as gio::application::ApplicationExtManual>::run::h5ad5b4b89b00f063
>   21:     0x559ad36e6ba3 - <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::h0cd3bedbb540ac3e
>   22:     0x559ad36c1ad3 - <futures_lite::future::PollFn<F> as core::future::future::Future>::poll::h67a3a8667bf91abd
>   23:     0x559ad36f1f1b - async_std::task::builder::Builder::blocking::ha51a286a0b922b13
>   24:     0x559ad372430c - blue_recorder::main::h05fec46f585020e9
>   25:     0x559ad3729d33 - std::sys::backtrace::__rust_begin_short_backtrace::h00a1fd4b96f972ac
>   26:     0x559ad3711459 - std::rt::lang_start::{{closure}}::h8c4342eb2e2bd770
>   27:     0x559ad3b173a5 - std::rt::lang_start_internal::h2084fce485147f46
>   28:     0x559ad3724345 - main
>   29:     0x7f8121ee527e - __libc_start_call_main
>   30:     0x7f8121ee5339 - __libc_start_main_alias_2
>   31:     0x559ad36290b5 - _start
>   32:                0x0 - <unknown>
> thread caused non-unwinding panic. aborting.
> fish: Job 1, 'RUST_BACKTRACE=1 blue-recorder' terminated by signal SIGABRT (Abort)
> ```

the error message happen because the application cannot found PO/Locales directory
